export const PROJECTS_MOCK = [
  {
    id: 1,
    name: 'Torres del Sol',
    location: 'Bogotá, Colombia',
    apartments: 120,
    priceFrom: 280000000,
    image: '/api/placeholder/300/200',
    status: 'En construcción',
    deliveryDate: '2025-12-01',
    description: 'Moderno proyecto residencial en el corazón de Bogotá, con excelente conectividad y servicios.',
    features: ['Zonas verdes', 'Gimnasio', 'Piscina', 'Jardín infantil', 'Seguridad 24/7'],
  },
  {
    id: 2,
    name: 'Residencial Los Robles',
    location: 'Medellín, Colombia',
    apartments: 85,
    priceFrom: 320000000,
    image: '/api/placeholder/300/200',
    status: 'Preventa',
    deliveryDate: '2026-06-01',
    description: 'Lujoso desarrollo en Medellín con vista panorámica y acabados de primera calidad.',
    features: ['Terraza con vista', 'Spa', 'Cinema', 'Club social', 'Concierge'],
  },
  {
    id: 3,
    name: 'Vista Hermosa',
    location: 'Cali, Colombia',
    apartments: 200,
    priceFrom: 250000000,
    image: '/api/placeholder/300/200',
    status: 'Entregado',
    deliveryDate: '2024-08-01',
    description: 'Gran proyecto familiar en Cali con espacios amplios y áreas de recreación.',
    features: ['Canchas deportivas', 'Parque', 'Salón comunal', 'Estacionamiento', 'Bodegas'],
  },
  {
    id: 4,
    name: 'Conjunto El Prado',
    location: 'Barranquilla, Colombia',
    apartments: 95,
    priceFrom: 180000000,
    image: '/api/placeholder/300/200',
    status: 'Preventa',
    deliveryDate: '2025-09-01',
    description: 'Proyecto con enfoque en el Caribe colombiano, pensado para familias jóvenes.',
    features: ['Coworking', 'Piscinas infantiles', 'Terraza BBQ', 'Salón social'],
  },
  {
    id: 5,
    name: 'Residencias Altamira',
    location: 'Bucaramanga, Colombia',
    apartments: 150,
    priceFrom: 220000000,
    image: '/api/placeholder/300/200',
    status: 'En construcción',
    deliveryDate: '2025-11-01',
    description: 'Viviendas con excelente ubicación y zonas verdes pensadas para el bienestar.',
    features: ['Gimnasio al aire libre', 'Parque infantil', 'Zona de mascotas', 'Senderos verdes'],
  },
  {
    id: 6,
    name: 'Torres del Norte',
    location: 'Pereira, Colombia',
    apartments: 75,
    priceFrom: 195000000,
    image: '/api/placeholder/300/200',
    status: 'Preventa',
    deliveryDate: '2026-03-01',
    description: 'Torre residencial con espacios modernos y vista privilegiada.',
    features: ['Sky lounge', 'Salón de juegos', 'Parqueaderos cubiertos', 'Lobby con portería 24/7'],
  },
  {
    id: 7,
    name: 'Villa del Sol',
    location: 'Manizales, Colombia',
    apartments: 110,
    priceFrom: 210000000,
    image: '/api/placeholder/300/200',
    status: 'En construcción',
    deliveryDate: '2025-10-01',
    description: 'Conjunto pensado para integrarse con la naturaleza y vistas sobre la ciudad.',
    features: ['Mirador panorámico', 'Zona de picnic', 'Piscina climatizada', 'Zona húmeda'],
  },
  {
    id: 8,
    name: 'Jardines del Sur',
    location: 'Neiva, Colombia',
    apartments: 60,
    priceFrom: 165000000,
    image: '/api/placeholder/300/200',
    status: 'Preventa',
    deliveryDate: '2026-01-01',
    description: 'Proyecto acogedor con énfasis en zonas verdes y espacios comunes.',
    features: ['Huerta urbana', 'Zona infantil', 'Salón comunal', 'Piscina familiar'],
  },
  {
    id: 9,
    name: 'Urbanización San Martín',
    location: 'Cartagena, Colombia',
    apartments: 180,
    priceFrom: 240000000,
    image: '/api/placeholder/300/200',
    status: 'Entregado',
    deliveryDate: '2024-05-01',
    description: 'Complejo residencial cerca al mar con amenidades premium.',
    features: ['Piscina infinita', 'Club house', 'Zona de juegos', 'Kioskos BBQ'],
  },
  {
    id: 10,
    name: 'Conjunto Los Laureles',
    location: 'Santa Marta, Colombia',
    apartments: 95,
    priceFrom: 195000000,
    image: '/api/placeholder/300/200',
    status: 'Preventa',
    deliveryDate: '2026-02-01',
    description: 'Desarrollo moderno con enfoque vacacional y espacios sociales.',
    features: ['Zona de coworking', 'Piscina con borde infinito', 'Lobby tipo hotel', 'Gimnasio'],
  },
  {
    id: 11,
    name: 'Residencial El Carmen',
    location: 'Ibagué, Colombia',
    apartments: 70,
    priceFrom: 170000000,
    image: '/api/placeholder/300/200',
    status: 'En construcción',
    deliveryDate: '2025-08-01',
    description: 'Residencias diseñadas para familias que buscan tranquilidad y comodidad.',
    features: ['Parque central', 'Cancha múltiple', 'Zona de lectura', 'Salón múltiple'],
  },
  {
    id: 12,
    name: 'Torres del Centro',
    location: 'Armenia, Colombia',
    apartments: 120,
    priceFrom: 205000000,
    image: '/api/placeholder/300/200',
    status: 'Preventa',
    deliveryDate: '2026-04-01',
    description: 'Proyecto vertical con cercanía a centros comerciales y universidades.',
    features: ['Salón social', 'Zona de estudio', 'Portería inteligente', 'Zona de mascotas'],
  },
];

export const ProjectsService = {
  async list() {
    // Simulación de petición HTTP
    await new Promise((resolve) => setTimeout(resolve, 300));
    return PROJECTS_MOCK;
  },
  async detail(projectId) {
    await new Promise((resolve) => setTimeout(resolve, 150));
    return PROJECTS_MOCK.find((project) => project.id === Number(projectId)) ?? null;
  },
  featured(count = 3) {
    return PROJECTS_MOCK.slice(0, count);
  },
};

